/// Problem Two:
/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
/// By starting with 1 and 2, the first 10 terms will be:

/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

int problemTwo(int aNumber)
{
	int term1 = 1;
	int term2 = 0;
	int temp;
	int const TERM_LIMIT = 4000000;
	int sum = 0;

	while (aNumber >= 0)
	{
		if (term1 >= TERM_LIMIT || term2 >= TERM_LIMIT)
		{
			return sum;
		}
		if (term1 % 2 == 0)
		{
			sum += term1;
		}

		temp = term1;
		term1 = term1 + term2;
		term2 = temp;
		aNumber--;
	}
}